### PR TITLE
Add ODBC driver

### PR DESCRIPTION
**Pull request by shadiakiki1986**
Hello. Thanks for this repository. This PR adds support for the [PDO ODBC driver](http://php.net/manual/en/ref.pdo-odbc.php). I also added some documentation in the readme. Let me know what you think

### CODE REVIEW

**Comment by shadiakiki1986** [comment]
About the failed travis build, the error is for php 5.6 and hhvm about using `string` for type hinting.
In PHP 7, that's fine, and is in fact required from `phpcs`.
Check this [SO](http://stackoverflow.com/a/5724696/4126114) answer as a reference.
I'm not sure what's the right way to deal with this to pass on both php 7 and php 5.6

**Comment by ofbeaton** [comment]
Thank you for taking the time to put this together.

To fix the phpcs warning, you have to remove the `string` type hint as we are targeting php 5.6. There was a typo in phpcs.xml.dist's `php_version` lock that kept phpcs from correctly figuring out what version we were targeting, I've now fixed it in master. Please update your branch and re-run your tests.

The readme should also now indicate that `odbc` is supported, please update this PR.

**Comment by shadiakiki1986** [comment]
Done

**Comment by ofbeaton** [comment]
Thank you for your work! I'll put out a phar release for this later today.

**Comment by ofbeaton** [comment]
During testing I found a bug introduced by this PR. Unfortunate because I haven't had a chance to add a test suite yet, which surely would have caught it.

```bash
# php build/db-ping.phar mysql --host localhost
DB-PING localhost:3306
time=2017-01-19 22:20:16, from localhost:3306, connected., delay=2000ms, repeat=1x, exec=0ms, since success=0s, since fail=0s, 8
time=2017-01-19 22:20:16, from localhost:3306, check passed., delay=2000ms, repeat=1x, exec=0ms, since success=0s, since fail=0s, 8
time=2017-01-19 22:20:18, from localhost:3306, check passed., delay=2000ms, repeat=1x, exec=0ms, since success=2.0174s, since fail=0s, 8
time=2017-01-19 22:20:20, from localhost:3306, check passed., delay=2000ms, repeat=1x, exec=0ms, since success=4.0191s, since fail=0s, 8
time=2017-01-19 22:20:22, from localhost:3306, check passed., delay=2000ms, repeat=1x, exec=0ms, since success=6.0208s, since fail=0s, 8
time=2017-01-19 22:20:24, from localhost:3306, check passed., delay=2000ms, repeat=1x, exec=0ms, since success=8.0229s, since fail=0s, 8
time=2017-01-19 22:20:26, from localhost:3306, check passed., delay=2000ms, repeat=1x, exec=0ms, since success=10.0248s, since fail=0s, 8
time=2017-01-19 22:20:28, from localhost:3306, check passed., delay=2000ms, repeat=1x, exec=0ms, since success=12.0265s, since fail=0s, 8
time=2017-01-19 22:20:30, from localhost:3306, check passed., delay=2000ms, repeat=1x, exec=0ms, since success=14.0282s, since fail=0s, 8
time=2017-01-19 22:20:32, from localhost:3306, check passed., delay=2000ms, repeat=1x, exec=0ms, since success=16.0299s, since fail=0s, 8
time=2017-01-19 22:20:34, from localhost:3306, check passed., delay=2000ms, repeat=1x, exec=0ms, since success=18.0317s, since fail=0s, 8
time=2017-01-19 22:20:36, from localhost:3306, check passed., delay=2000ms, repeat=1x, exec=0ms, since success=20.0334s, since fail=0s, 8
time=2017-01-19 22:20:38, from localhost:3306, check passed., delay=2000ms, repeat=1x, exec=0ms, since success=22.0355s, since fail=0s, 8
time=2017-01-19 22:20:40, from localhost:3306, check passed., delay=2000ms, repeat=1x, exec=0ms, since success=24.0373s, since fail=0s, 8
-- localhost:3306 database ping statistics ---
13 tries, 13 successes, 0 failures, 0% fail tries
24.8725s time, 24.8725s success, 0s fail, 0% fail time
```

Notice the trailing `, 8` on each line.

I think it has to do with your format processing code and the `a` flag, but I'll have to debug it when I have a chance later. If you have time, please submit another PR with a fix.

**Pull request merged**
